name: Node.js CI
run-name: Build code by ${{ github.actor }} from '${{ github.event.head_commit.message }}''

on:
  push:
    branches: ["main"]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        name: Node.js ⇒ 20.x
        with:
          node-version: 20.x
          cache: "npm"

      - name: npm ⇒ Install dependencies
        run: npm install

      - name: "Building..."
        run: npm run start
        env:
          NODE_ENV: production
        continue-on-error: false

      - name: Save Changes ⇒ Commit builded code
        run: |
          git config --global user.name '${{ github.event.head_commit.author.name }}'
          git config --global user.email '${{ github.event.head_commit.author.username }}@${{ github.event.head_commit.author.email }}'
          git add .
          git commit -m '${{ github.event.head_commit.message }} (build html files)'
          git fetch
          git pull
          git push origin main:gh-pages
        continue-on-error: true